### ISSUE TITLE
Error in Lambda when launching the Skill

### ISSUE THREAD

**Issue by ardimaunahan** [alexa/skill-sample-nodejs-web-api-my-cactus#24]
I was able to successfully do `ask deploy` and `npm run uploadS3` inside the webapp. However, when launching the skill, there is an error in Lambda function. What could be the cause of this error during the launch?

`2020-10-27T17:39:36.522Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module './dispatcher/error/mapper/GenericErrorMapper'\nRequire stack:\n- /var/task/node_modules/ask-sdk-runtime/dist/index.js\n- /var/task/node_modules/ask-sdk-core/dist/attributes/AttributesManagerFactory.js\n- /var/task/node_modules/ask-sdk-core/dist/index.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module './dispatcher/error/mapper/GenericErrorMapper'","Require stack:","- /var/task/node_modules/ask-sdk-runtime/dist/index.js","- /var/task/node_modules/ask-sdk-core/dist/attributes/AttributesManagerFactory.js","- /var/task/node_modules/ask-sdk-core/dist/index.js","- /var/task/index.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1137:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)","    at Module.load (internal/modules/cjs/loader.js:985:32)","    at Function.Module._load (internal/modules/cjs/loader.js:878:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)","    at internal/main/run_main_module.js:17:47"]}`

I also noticed that the runtime is still using Node 10.x. I manually change it to 12.x but same problem.

**Comment by ardimaunahan** [comment]
I was able to resolve it via rebuilding the project again. Perhaps related to this issue: https://github.com/alexa/ask-cli/issues/59
